"""Additional starter cuisines: Mexican, Japanese, Chinese, Thai, Mediterranean, American.

Each cuisine: 5 vegetarian + 5 non-vegetarian recipes.
"""
from typing import Any, Dict, List

MORE_STARTER_RECIPES: List[Dict[str, Any]] = [
    # —— Mexican · Vegetarian (5) ——
    {
        "cuisine": "Mexican",
        "diet": "Vegetarian",
        "name": "Vegetarian Burrito Bowl",
        "description": "Rice, black beans, corn, salsa, and guacamole in a bowl.",
        "instructions": "1. Cook rice with lime and cilantro.\n2. Warm beans with cumin and garlic.\n3. Char corn in a hot pan.\n4. Assemble bowls with salsa, lettuce, and guacamole.",
        "prep_time": 15,
        "cook_time": 25,
        "servings": 4,
        "calories_kcal": 1200,
        "protein_g": 36,
        "carbs_g": 180,
        "fat_g": 36,
        "ingredients": [
            {"name": "rice", "quantity": 300, "unit": "g", "category": "grains"},
            {"name": "black beans", "quantity": 400, "unit": "g", "category": "grains"},
            {"name": "corn kernels", "quantity": 200, "unit": "g", "category": "vegetables"},
            {"name": "avocado", "quantity": 2, "unit": "piece", "category": "fruits"},
            {"name": "salsa", "quantity": 200, "unit": "g", "category": "vegetables"},
        ],
    },
    {
        "cuisine": "Mexican",
        "diet": "Vegetarian",
        "name": "Cheese Quesadillas",
        "description": "Crispy tortillas filled with melted cheese and peppers.",
        "instructions": "1. Sauté sliced peppers and onion.\n2. Fill tortillas with cheese and vegetables.\n3. Cook in a dry pan until golden both sides.\n4. Cut into wedges; serve with salsa and sour cream.",
        "prep_time": 10,
        "cook_time": 15,
        "servings": 4,
        "calories_kcal": 1000,
        "protein_g": 40,
        "carbs_g": 80,
        "fat_g": 56,
        "ingredients": [
            {"name": "flour tortillas", "quantity": 8, "unit": "piece", "category": "grains"},
            {"name": "cheddar cheese", "quantity": 300, "unit": "g", "category": "dairy"},
            {"name": "bell pepper", "quantity": 2, "unit": "piece", "category": "vegetables"},
            {"name": "onion", "quantity": 1, "unit": "piece", "category": "vegetables"},
            {"name": "sour cream", "quantity": 100, "unit": "g", "category": "dairy"},
        ],
    },
    {
        "cuisine": "Mexican",
        "diet": "Vegetarian",
        "name": "Vegetarian Enchiladas",
        "description": "Corn tortillas rolled with beans and cheese, baked in red sauce.",
        "instructions": "1. Fill tortillas with beans, cheese, and sautéed vegetables.\n2. Roll and place in a baking dish.\n3. Cover with enchilada sauce and more cheese.\n4. Bake until bubbling; top with cilantro.",
        "prep_time": 20,
        "cook_time": 25,
        "servings": 4,
        "calories_kcal": 1100,
        "protein_g": 44,
        "carbs_g": 120,
        "fat_g": 48,
        "ingredients": [
            {"name": "corn tortillas", "quantity": 8, "unit": "piece", "category": "grains"},
            {"name": "pinto beans", "quantity": 400, "unit": "g", "category": "grains"},
            {"name": "enchilada sauce", "quantity": 400, "unit": "ml", "category": "vegetables"},
            {"name": "monterey jack cheese", "quantity": 250, "unit": "g", "category": "dairy"},
            {"name": "zucchini", "quantity": 2, "unit": "piece", "category": "vegetables"},
        ],
    },
    {
        "cuisine": "Mexican",
        "diet": "Vegetarian",
        "name": "Mexican Street Corn Salad",
        "description": "Charred corn with cotija, lime, and chili-lime dressing.",
        "instructions": "1. Char corn in a hot skillet.\n2. Mix mayo, lime juice, chili powder, and cotija.\n3. Toss corn with dressing and cilantro.\n4. Serve warm or at room temperature.",
        "prep_time": 10,
        "cook_time": 10,
        "servings": 4,
        "calories_kcal": 720,
        "protein_g": 20,
        "carbs_g": 88,
        "fat_g": 36,
        "ingredients": [
            {"name": "corn on the cob", "quantity": 4, "unit": "piece", "category": "vegetables"},
            {"name": "cotija cheese", "quantity": 100, "unit": "g", "category": "dairy"},
            {"name": "lime", "quantity": 2, "unit": "piece", "category": "fruits"},
            {"name": "chili powder", "quantity": 1, "unit": "tsp", "category": "spices"},
            {"name": "fresh cilantro", "quantity": 20, "unit": "g", "category": "vegetables"},
        ],
    },
    {
        "cuisine": "Mexican",
        "diet": "Vegetarian",
        "name": "Spicy Black Bean Tacos",
        "description": "Soft tacos with seasoned black beans and fresh toppings.",
        "instructions": "1. Simmer beans with cumin, garlic, and chipotle.\n2. Warm tortillas.\n3. Fill with beans, cabbage slaw, and pico de gallo.\n4. Finish with lime and hot sauce.",
        "prep_time": 15,
        "cook_time": 15,
        "servings": 4,
        "calories_kcal": 880,
        "protein_g": 32,
        "carbs_g": 128,
        "fat_g": 24,
        "ingredients": [
            {"name": "black beans", "quantity": 400, "unit": "g", "category": "grains"},
            {"name": "corn tortillas", "quantity": 12, "unit": "piece", "category": "grains"},
            {"name": "cabbage", "quantity": 200, "unit": "g", "category": "vegetables"},
            {"name": "tomato", "quantity": 2, "unit": "piece", "category": "vegetables"},
            {"name": "chipotle in adobo", "quantity": 1, "unit": "tbsp", "category": "spices"},
        ],
    },
    # —— Mexican · Non-vegetarian (5) ——
    {
        "cuisine": "Mexican",
        "diet": "Non-vegetarian",
        "name": "Chicken Tacos al Pastor",
        "description": "Marinated grilled chicken tacos with pineapple and onion.",
        "instructions": "1. Marinate chicken with achiote, citrus, and spices.\n2. Grill or sear until cooked through.\n3. Dice and serve on warm tortillas with pineapple and cilantro.\n4. Add salsa verde to taste.",
        "prep_time": 20,
        "cook_time": 20,
        "servings": 4,
        "calories_kcal": 1200,
        "protein_g": 96,
        "carbs_g": 80,
        "fat_g": 48,
        "ingredients": [
            {"name": "chicken thigh", "quantity": 600, "unit": "g", "category": "poultry"},
            {"name": "pineapple", "quantity": 200, "unit": "g", "category": "fruits"},
            {"name": "corn tortillas", "quantity": 12, "unit": "piece", "category": "grains"},
            {"name": "onion", "quantity": 1, "unit": "piece", "category": "vegetables"},
            {"name": "achiote paste", "quantity": 2, "unit": "tbsp", "category": "spices"},
        ],
    },
    {
        "cuisine": "Mexican",
        "diet": "Non-vegetarian",
        "name": "Beef Burritos",
        "description": "Large flour tortillas stuffed with seasoned ground beef and rice.",
        "instructions": "1. Brown beef with taco seasoning.\n2. Warm rice and beans.\n3. Fill tortillas, roll tightly.\n4. Optional: toast seam-side down in a pan.",
        "prep_time": 15,
        "cook_time": 20,
        "servings": 4,
        "calories_kcal": 1800,
        "protein_g": 88,
        "carbs_g": 160,
        "fat_g": 80,
        "ingredients": [
            {"name": "ground beef", "quantity": 500, "unit": "g", "category": "meat"},
            {"name": "flour tortillas", "quantity": 4, "unit": "piece", "category": "grains"},
            {"name": "rice", "quantity": 250, "unit": "g", "category": "grains"},
            {"name": "refried beans", "quantity": 300, "unit": "g", "category": "grains"},
            {"name": "taco seasoning", "quantity": 2, "unit": "tbsp", "category": "spices"},
        ],
    },
    {
        "cuisine": "Mexican",
        "diet": "Non-vegetarian",
        "name": "Shrimp Ceviche Tostadas",
        "description": "Lime-cured shrimp on crispy tostadas with avocado.",
        "instructions": "1. Dice shrimp; marinate in lime juice until opaque.\n2. Mix with onion, cilantro, and chili.\n3. Drain slightly; top tostadas with ceviche and avocado.\n4. Serve immediately.",
        "prep_time": 25,
        "cook_time": 0,
        "servings": 4,
        "calories_kcal": 640,
        "protein_g": 72,
        "carbs_g": 48,
        "fat_g": 16,
        "ingredients": [
            {"name": "shrimp", "quantity": 400, "unit": "g", "category": "seafood"},
            {"name": "lime juice", "quantity": 200, "unit": "ml", "category": "fruits"},
            {"name": "corn tostadas", "quantity": 8, "unit": "piece", "category": "grains"},
            {"name": "avocado", "quantity": 2, "unit": "piece", "category": "fruits"},
            {"name": "red onion", "quantity": 1, "unit": "piece", "category": "vegetables"},
        ],
    },
    {
        "cuisine": "Mexican",
        "diet": "Non-vegetarian",
        "name": "Carnitas",
        "description": "Slow-braised pork shoulder shredded for tacos.",
        "instructions": "1. Season pork; sear in a heavy pot.\n2. Add orange juice, garlic, and bay leaf; braise until tender.\n3. Shred meat; crisp under broiler if desired.\n4. Serve in tortillas with onion and cilantro.",
        "prep_time": 20,
        "cook_time": 150,
        "servings": 4,
        "calories_kcal": 2000,
        "protein_g": 120,
        "carbs_g": 32,
        "fat_g": 144,
        "ingredients": [
            {"name": "pork shoulder", "quantity": 800, "unit": "g", "category": "pork"},
            {"name": "orange juice", "quantity": 250, "unit": "ml", "category": "fruits"},
            {"name": "garlic", "quantity": 6, "unit": "clove", "category": "vegetables"},
            {"name": "corn tortillas", "quantity": 12, "unit": "piece", "category": "grains"},
            {"name": "bay leaf", "quantity": 2, "unit": "piece", "category": "spices"},
        ],
    },
    {
        "cuisine": "Mexican",
        "diet": "Non-vegetarian",
        "name": "Fish Tacos Baja Style",
        "description": "Beer-battered fish tacos with cabbage slaw and crema.",
        "instructions": "1. Mix batter; fry fish until golden.\n2. Toss cabbage with lime and salt.\n3. Warm tortillas.\n4. Assemble with fish, slaw, and crema.",
        "prep_time": 20,
        "cook_time": 15,
        "servings": 4,
        "calories_kcal": 1400,
        "protein_g": 80,
        "carbs_g": 96,
        "fat_g": 72,
        "ingredients": [
            {"name": "white fish fillet", "quantity": 600, "unit": "g", "category": "fish"},
            {"name": "flour", "quantity": 150, "unit": "g", "category": "grains"},
            {"name": "corn tortillas", "quantity": 12, "unit": "piece", "category": "grains"},
            {"name": "cabbage", "quantity": 200, "unit": "g", "category": "vegetables"},
            {"name": "mexican crema", "quantity": 100, "unit": "ml", "category": "dairy"},
        ],
    },
    # —— Japanese · Vegetarian (5) ——
    {
        "cuisine": "Japanese",
        "diet": "Vegetarian",
        "name": "Vegetable Maki Rolls",
        "description": "Sushi rolls with cucumber, avocado, and pickled radish.",
        "instructions": "1. Season sushi rice with rice vinegar.\n2. Place nori on a mat; spread rice.\n3. Add fillings; roll tightly.\n4. Slice with a wet knife; serve with soy and wasabi.",
        "prep_time": 30,
        "cook_time": 20,
        "servings": 4,
        "calories_kcal": 960,
        "protein_g": 16,
        "carbs_g": 176,
        "fat_g": 20,
        "ingredients": [
            {"name": "sushi rice", "quantity": 400, "unit": "g", "category": "grains"},
            {"name": "nori sheets", "quantity": 4, "unit": "piece", "category": "other"},
            {"name": "cucumber", "quantity": 1, "unit": "piece", "category": "vegetables"},
            {"name": "avocado", "quantity": 2, "unit": "piece", "category": "fruits"},
            {"name": "rice vinegar", "quantity": 3, "unit": "tbsp", "category": "other"},
        ],
    },
    {
        "cuisine": "Japanese",
        "diet": "Vegetarian",
        "name": "Miso Soup",
        "description": "Classic dashi-based soup with tofu and wakame.",
        "instructions": "1. Warm dashi stock.\n2. Dissolve miso off the heat.\n3. Add tofu and rehydrated wakame.\n4. Garnish with scallions; do not boil after miso is added.",
        "prep_time": 5,
        "cook_time": 10,
        "servings": 4,
        "calories_kcal": 320,
        "protein_g": 24,
        "carbs_g": 20,
        "fat_g": 12,
        "ingredients": [
            {"name": "miso paste", "quantity": 4, "unit": "tbsp", "category": "other"},
            {"name": "silken tofu", "quantity": 300, "unit": "g", "category": "other"},
            {"name": "dried wakame", "quantity": 10, "unit": "g", "category": "vegetables"},
            {"name": "dashi stock", "quantity": 1, "unit": "L", "category": "other"},
            {"name": "scallion", "quantity": 2, "unit": "piece", "category": "vegetables"},
        ],
    },
    {
        "cuisine": "Japanese",
        "diet": "Vegetarian",
        "name": "Vegetable Tempura",
        "description": "Lightly battered and fried seasonal vegetables.",
        "instructions": "1. Cut vegetables into bite-size pieces.\n2. Mix cold water and flour for batter (do not overmix).\n3. Fry vegetables until crisp and pale gold.\n4. Serve with tentsuyu dipping sauce.",
        "prep_time": 20,
        "cook_time": 15,
        "servings": 4,
        "calories_kcal": 800,
        "protein_g": 12,
        "carbs_g": 96,
        "fat_g": 40,
        "ingredients": [
            {"name": "sweet potato", "quantity": 2, "unit": "piece", "category": "vegetables"},
            {"name": "broccoli", "quantity": 200, "unit": "g", "category": "vegetables"},
            {"name": "shiitake mushroom", "quantity": 150, "unit": "g", "category": "vegetables"},
            {"name": "flour", "quantity": 150, "unit": "g", "category": "grains"},
            {"name": "vegetable oil", "quantity": 500, "unit": "ml", "category": "other"},
        ],
    },
    {
        "cuisine": "Japanese",
        "diet": "Vegetarian",
        "name": "Edamame Rice Bowl",
        "description": "Steamed rice topped with edamame, sesame, and soy glaze.",
        "instructions": "1. Cook rice.\n2. Boil edamame; season with salt.\n3. Arrange rice in bowls; top with edamame and shredded nori.\n4. Drizzle soy and sesame oil.",
        "prep_time": 10,
        "cook_time": 20,
        "servings": 4,
        "calories_kcal": 880,
        "protein_g": 36,
        "carbs_g": 140,
        "fat_g": 20,
        "ingredients": [
            {"name": "japanese rice", "quantity": 400, "unit": "g", "category": "grains"},
            {"name": "edamame", "quantity": 300, "unit": "g", "category": "vegetables"},
            {"name": "soy sauce", "quantity": 3, "unit": "tbsp", "category": "other"},
            {"name": "sesame oil", "quantity": 1, "unit": "tbsp", "category": "other"},
            {"name": "sesame seeds", "quantity": 2, "unit": "tbsp", "category": "spices"},
        ],
    },
    {
        "cuisine": "Japanese",
        "diet": "Vegetarian",
        "name": "Teriyaki Tofu Bowl",
        "description": "Crispy tofu glazed with homemade teriyaki over rice.",
        "instructions": "1. Press and cube tofu; pan-fry until golden.\n2. Simmer soy, mirin, sugar, and ginger for glaze.\n3. Coat tofu in glaze.\n4. Serve over rice with steamed broccoli.",
        "prep_time": 15,
        "cook_time": 20,
        "servings": 4,
        "calories_kcal": 1000,
        "protein_g": 48,
        "carbs_g": 120,
        "fat_g": 32,
        "ingredients": [
            {"name": "firm tofu", "quantity": 500, "unit": "g", "category": "other"},
            {"name": "japanese rice", "quantity": 350, "unit": "g", "category": "grains"},
            {"name": "soy sauce", "quantity": 4, "unit": "tbsp", "category": "other"},
            {"name": "mirin", "quantity": 3, "unit": "tbsp", "category": "other"},
            {"name": "broccoli", "quantity": 300, "unit": "g", "category": "vegetables"},
        ],
    },
    # —— Japanese · Non-vegetarian (5) ——
    {
        "cuisine": "Japanese",
        "diet": "Non-vegetarian",
        "name": "Salmon Nigiri Platter",
        "description": "Hand-pressed sushi rice topped with fresh salmon slices.",
        "instructions": "1. Cook and season sushi rice; cool to body temperature.\n2. Slice salmon against the grain.\n3. Wet hands; form rice ovals; top with salmon and wasabi.\n4. Serve with soy and pickled ginger.",
        "prep_time": 25,
        "cook_time": 20,
        "servings": 4,
        "calories_kcal": 1200,
        "protein_g": 72,
        "carbs_g": 160,
        "fat_g": 24,
        "ingredients": [
            {"name": "sushi rice", "quantity": 400, "unit": "g", "category": "grains"},
            {"name": "salmon fillet", "quantity": 400, "unit": "g", "category": "fish"},
            {"name": "rice vinegar", "quantity": 2, "unit": "tbsp", "category": "other"},
            {"name": "soy sauce", "quantity": 4, "unit": "tbsp", "category": "other"},
            {"name": "wasabi", "quantity": 1, "unit": "tsp", "category": "spices"},
        ],
    },
    {
        "cuisine": "Japanese",
        "diet": "Non-vegetarian",
        "name": "Chicken Teriyaki",
        "description": "Grilled chicken thighs with glossy teriyaki sauce.",
        "instructions": "1. Marinate chicken in teriyaki sauce.\n2. Grill or pan-sear until cooked.\n3. Reduce remaining sauce until thick.\n4. Slice chicken; serve with rice and vegetables.",
        "prep_time": 15,
        "cook_time": 20,
        "servings": 4,
        "calories_kcal": 1400,
        "protein_g": 96,
        "carbs_g": 120,
        "fat_g": 48,
        "ingredients": [
            {"name": "chicken thigh", "quantity": 700, "unit": "g", "category": "poultry"},
            {"name": "soy sauce", "quantity": 5, "unit": "tbsp", "category": "other"},
            {"name": "mirin", "quantity": 4, "unit": "tbsp", "category": "other"},
            {"name": "japanese rice", "quantity": 350, "unit": "g", "category": "grains"},
            {"name": "ginger", "quantity": 1, "unit": "tbsp", "category": "vegetables"},
        ],
    },
    {
        "cuisine": "Japanese",
        "diet": "Non-vegetarian",
        "name": "Tuna Sashimi Bowl",
        "description": "Sushi rice bowl with sashimi-grade tuna and toppings.",
        "instructions": "1. Cook sushi rice; cool slightly.\n2. Slice tuna into cubes.\n3. Arrange rice in bowls; top with tuna, cucumber, and avocado.\n4. Add soy, sesame, and nori strips.",
        "prep_time": 20,
        "cook_time": 15,
        "servings": 4,
        "calories_kcal": 1100,
        "protein_g": 80,
        "carbs_g": 140,
        "fat_g": 20,
        "ingredients": [
            {"name": "sushi-grade tuna", "quantity": 400, "unit": "g", "category": "fish"},
            {"name": "sushi rice", "quantity": 400, "unit": "g", "category": "grains"},
            {"name": "cucumber", "quantity": 1, "unit": "piece", "category": "vegetables"},
            {"name": "avocado", "quantity": 1, "unit": "piece", "category": "fruits"},
            {"name": "soy sauce", "quantity": 3, "unit": "tbsp", "category": "other"},
        ],
    },
    {
        "cuisine": "Japanese",
        "diet": "Non-vegetarian",
        "name": "Shrimp Tempura Udon",
        "description": "Thick udon noodles in broth with crispy shrimp tempura.",
        "instructions": "1. Cook udon; prepare hot dashi broth.\n2. Batter and fry shrimp tempura.\n3. Serve udon in broth topped with tempura.\n4. Garnish with scallion and fish cake if using.",
        "prep_time": 15,
        "cook_time": 20,
        "servings": 4,
        "calories_kcal": 1300,
        "protein_g": 56,
        "carbs_g": 180,
        "fat_g": 40,
        "ingredients": [
            {"name": "udon noodles", "quantity": 400, "unit": "g", "category": "grains"},
            {"name": "shrimp", "quantity": 400, "unit": "g", "category": "seafood"},
            {"name": "dashi stock", "quantity": 1.2, "unit": "L", "category": "other"},
            {"name": "flour", "quantity": 100, "unit": "g", "category": "grains"},
            {"name": "scallion", "quantity": 2, "unit": "piece", "category": "vegetables"},
        ],
    },
    {
        "cuisine": "Japanese",
        "diet": "Non-vegetarian",
        "name": "Gyudon Beef Bowl",
        "description": "Simmered thin beef and onions over steamed rice.",
        "instructions": "1. Slice beef and onion thinly.\n2. Simmer with dashi, soy, mirin, and sugar.\n3. Cook until beef is tender and sauce reduces.\n4. Serve over rice; optional soft egg on top.",
        "prep_time": 15,
        "cook_time": 15,
        "servings": 4,
        "calories_kcal": 1600,
        "protein_g": 72,
        "carbs_g": 160,
        "fat_g": 64,
        "ingredients": [
            {"name": "thinly sliced beef", "quantity": 500, "unit": "g", "category": "meat"},
            {"name": "onion", "quantity": 2, "unit": "piece", "category": "vegetables"},
            {"name": "japanese rice", "quantity": 400, "unit": "g", "category": "grains"},
            {"name": "soy sauce", "quantity": 4, "unit": "tbsp", "category": "other"},
            {"name": "mirin", "quantity": 3, "unit": "tbsp", "category": "other"},
        ],
    },
    # —— Chinese · Vegetarian (5) ——
    {
        "cuisine": "Chinese",
        "diet": "Vegetarian",
        "name": "Vegetable Fried Rice",
        "description": "Wok-fried rice with peas, carrots, and soy sauce.",
        "instructions": "1. Cook rice ahead and chill.\n2. Scramble optional tofu or skip; set aside.\n3. Stir-fry vegetables on high heat.\n4. Add rice and soy; toss until smoky and heated through.",
        "prep_time": 15,
        "cook_time": 10,
        "servings": 4,
        "calories_kcal": 880,
        "protein_g": 20,
        "carbs_g": 160,
        "fat_g": 16,
        "ingredients": [
            {"name": "cooked rice", "quantity": 600, "unit": "g", "category": "grains"},
            {"name": "peas", "quantity": 150, "unit": "g", "category": "vegetables"},
            {"name": "carrot", "quantity": 2, "unit": "piece", "category": "vegetables"},
            {"name": "soy sauce", "quantity": 3, "unit": "tbsp", "category": "other"},
            {"name": "sesame oil", "quantity": 1, "unit": "tbsp", "category": "other"},
        ],
    },
    {
        "cuisine": "Chinese",
        "diet": "Vegetarian",
        "name": "Mapo Tofu (Vegetarian)",
        "description": "Silken tofu in spicy bean sauce without meat.",
        "instructions": "1. Cube tofu; blanch gently.\n2. Fry doubanjiang, garlic, and mushrooms.\n3. Add stock; simmer tofu 5 minutes.\n4. Thicken with cornstarch slurry; top with scallions.",
        "prep_time": 10,
        "cook_time": 15,
        "servings": 4,
        "calories_kcal": 720,
        "protein_g": 40,
        "carbs_g": 32,
        "fat_g": 48,
        "ingredients": [
            {"name": "silken tofu", "quantity": 500, "unit": "g", "category": "other"},
            {"name": "shiitake mushroom", "quantity": 150, "unit": "g", "category": "vegetables"},
            {"name": "doubanjiang", "quantity": 2, "unit": "tbsp", "category": "spices"},
            {"name": "vegetable stock", "quantity": 300, "unit": "ml", "category": "other"},
            {"name": "scallion", "quantity": 2, "unit": "piece", "category": "vegetables"},
        ],
    },
    {
        "cuisine": "Chinese",
        "diet": "Vegetarian",
        "name": "Vegetable Spring Rolls",
        "description": "Crispy rolls filled with cabbage and glass noodles.",
        "instructions": "1. Stir-fry filling; cool.\n2. Roll in spring roll wrappers.\n3. Deep-fry or bake until golden.\n4. Serve with sweet chili sauce.",
        "prep_time": 30,
        "cook_time": 15,
        "servings": 4,
        "calories_kcal": 800,
        "protein_g": 16,
        "carbs_g": 96,
        "fat_g": 40,
        "ingredients": [
            {"name": "spring roll wrappers", "quantity": 12, "unit": "piece", "category": "grains"},
            {"name": "cabbage", "quantity": 300, "unit": "g", "category": "vegetables"},
            {"name": "glass noodles", "quantity": 80, "unit": "g", "category": "grains"},
            {"name": "carrot", "quantity": 2, "unit": "piece", "category": "vegetables"},
            {"name": "vegetable oil", "quantity": 400, "unit": "ml", "category": "other"},
        ],
    },
    {
        "cuisine": "Chinese",
        "diet": "Vegetarian",
        "name": "Bok Choy Garlic Stir Fry",
        "description": "Quick stir-fried bok choy with garlic and soy.",
        "instructions": "1. Halve bok choy.\n2. Heat oil; fry garlic until fragrant.\n3. Stir-fry bok choy on high heat 3–4 minutes.\n4. Season with soy and white pepper.",
        "prep_time": 10,
        "cook_time": 8,
        "servings": 4,
        "calories_kcal": 240,
        "protein_g": 12,
        "carbs_g": 24,
        "fat_g": 12,
        "ingredients": [
            {"name": "bok choy", "quantity": 600, "unit": "g", "category": "vegetables"},
            {"name": "garlic", "quantity": 6, "unit": "clove", "category": "vegetables"},
            {"name": "soy sauce", "quantity": 2, "unit": "tbsp", "category": "other"},
            {"name": "vegetable oil", "quantity": 2, "unit": "tbsp", "category": "other"},
            {"name": "white pepper", "quantity": 0.5, "unit": "tsp", "category": "spices"},
        ],
    },
    {
        "cuisine": "Chinese",
        "diet": "Vegetarian",
        "name": "Sweet and Sour Tofu",
        "description": "Crispy tofu tossed in tangy sweet-sour sauce with peppers.",
        "instructions": "1. Coat and fry tofu cubes until crisp.\n2. Stir-fry bell peppers and pineapple.\n3. Add vinegar, ketchup, sugar, and stock; thicken.\n4. Toss tofu in sauce; serve with rice.",
        "prep_time": 20,
        "cook_time": 20,
        "servings": 4,
        "calories_kcal": 960,
        "protein_g": 36,
        "carbs_g": 120,
        "fat_g": 36,
        "ingredients": [
            {"name": "firm tofu", "quantity": 500, "unit": "g", "category": "other"},
            {"name": "bell pepper", "quantity": 2, "unit": "piece", "category": "vegetables"},
            {"name": "pineapple chunks", "quantity": 200, "unit": "g", "category": "fruits"},
            {"name": "rice vinegar", "quantity": 3, "unit": "tbsp", "category": "other"},
            {"name": "tomato ketchup", "quantity": 4, "unit": "tbsp", "category": "other"},
        ],
    },
    # —— Chinese · Non-vegetarian (5) ——
    {
        "cuisine": "Chinese",
        "diet": "Non-vegetarian",
        "name": "Kung Pao Chicken",
        "description": "Stir-fried chicken with peanuts, chili, and vegetables.",
        "instructions": "1. Marinate diced chicken.\n2. Stir-fry dried chilies and Sichuan pepper.\n3. Cook chicken; add sauce and peanuts.\n4. Finish with scallions; serve with rice.",
        "prep_time": 15,
        "cook_time": 12,
        "servings": 4,
        "calories_kcal": 1200,
        "protein_g": 88,
        "carbs_g": 48,
        "fat_g": 72,
        "ingredients": [
            {"name": "chicken breast", "quantity": 600, "unit": "g", "category": "poultry"},
            {"name": "roasted peanuts", "quantity": 80, "unit": "g", "category": "other"},
            {"name": "dried red chili", "quantity": 8, "unit": "piece", "category": "spices"},
            {"name": "soy sauce", "quantity": 3, "unit": "tbsp", "category": "other"},
            {"name": "rice vinegar", "quantity": 2, "unit": "tbsp", "category": "other"},
        ],
    },
    {
        "cuisine": "Chinese",
        "diet": "Non-vegetarian",
        "name": "Sweet and Sour Pork",
        "description": "Battered pork pieces in classic sweet-sour sauce.",
        "instructions": "1. Coat pork; deep-fry until crisp.\n2. Prepare sauce with vinegar, sugar, and ketchup.\n3. Stir-fry peppers and pineapple.\n4. Combine pork and sauce; serve immediately.",
        "prep_time": 20,
        "cook_time": 20,
        "servings": 4,
        "calories_kcal": 1600,
        "protein_g": 72,
        "carbs_g": 128,
        "fat_g": 88,
        "ingredients": [
            {"name": "pork tenderloin", "quantity": 600, "unit": "g", "category": "pork"},
            {"name": "bell pepper", "quantity": 2, "unit": "piece", "category": "vegetables"},
            {"name": "pineapple chunks", "quantity": 200, "unit": "g", "category": "fruits"},
            {"name": "flour", "quantity": 120, "unit": "g", "category": "grains"},
            {"name": "rice vinegar", "quantity": 3, "unit": "tbsp", "category": "other"},
        ],
    },
    {
        "cuisine": "Chinese",
        "diet": "Non-vegetarian",
        "name": "Chicken Chow Mein",
        "description": "Stir-fried noodles with chicken and crisp vegetables.",
        "instructions": "1. Cook noodles; drain.\n2. Stir-fry chicken until done; remove.\n3. Stir-fry vegetables and aromatics.\n4. Toss noodles, chicken, and sauce on high heat.",
        "prep_time": 15,
        "cook_time": 12,
        "servings": 4,
        "calories_kcal": 1400,
        "protein_g": 80,
        "carbs_g": 160,
        "fat_g": 48,
        "ingredients": [
            {"name": "egg noodles", "quantity": 400, "unit": "g", "category": "grains"},
            {"name": "chicken breast", "quantity": 500, "unit": "g", "category": "poultry"},
            {"name": "bean sprouts", "quantity": 200, "unit": "g", "category": "vegetables"},
            {"name": "soy sauce", "quantity": 4, "unit": "tbsp", "category": "other"},
            {"name": "cabbage", "quantity": 200, "unit": "g", "category": "vegetables"},
        ],
    },
    {
        "cuisine": "Chinese",
        "diet": "Non-vegetarian",
        "name": "Steamed Whole Fish",
        "description": "Ginger-scallion steamed fish with soy finish.",
        "instructions": "1. Score fish; stuff with ginger.\n2. Steam 10–12 minutes per 500 g.\n3. Top with scallions; pour hot oil to sizzle.\n4. Drizzle soy around fish.",
        "prep_time": 10,
        "cook_time": 15,
        "servings": 4,
        "calories_kcal": 800,
        "protein_g": 96,
        "carbs_g": 8,
        "fat_g": 40,
        "ingredients": [
            {"name": "whole sea bass", "quantity": 800, "unit": "g", "category": "fish"},
            {"name": "ginger", "quantity": 40, "unit": "g", "category": "vegetables"},
            {"name": "scallion", "quantity": 4, "unit": "piece", "category": "vegetables"},
            {"name": "soy sauce", "quantity": 4, "unit": "tbsp", "category": "other"},
            {"name": "vegetable oil", "quantity": 3, "unit": "tbsp", "category": "other"},
        ],
    },
    {
        "cuisine": "Chinese",
        "diet": "Non-vegetarian",
        "name": "Pork Dumplings",
        "description": "Pan-fried and steamed dumplings with pork filling.",
        "instructions": "1. Mix pork with cabbage, ginger, and soy.\n2. Fill wrappers; pleat edges.\n3. Pan-fry bottom until golden; add water and steam.\n4. Serve with black vinegar dipping sauce.",
        "prep_time": 40,
        "cook_time": 20,
        "servings": 4,
        "calories_kcal": 1200,
        "protein_g": 64,
        "carbs_g": 96,
        "fat_g": 56,
        "ingredients": [
            {"name": "ground pork", "quantity": 400, "unit": "g", "category": "pork"},
            {"name": "dumpling wrappers", "quantity": 40, "unit": "piece", "category": "grains"},
            {"name": "napa cabbage", "quantity": 200, "unit": "g", "category": "vegetables"},
            {"name": "ginger", "quantity": 1, "unit": "tbsp", "category": "vegetables"},
            {"name": "soy sauce", "quantity": 2, "unit": "tbsp", "category": "other"},
        ],
    },
    # —— Thai · Vegetarian (5) ——
    {
        "cuisine": "Thai",
        "diet": "Vegetarian",
        "name": "Vegetable Green Curry",
        "description": "Coconut curry with Thai basil and mixed vegetables.",
        "instructions": "1. Fry green curry paste in coconut cream.\n2. Add vegetables and remaining coconut milk.\n3. Simmer until tender.\n4. Finish with basil and lime; serve with jasmine rice.",
        "prep_time": 15,
        "cook_time": 20,
        "servings": 4,
        "calories_kcal": 1000,
        "protein_g": 20,
        "carbs_g": 96,
        "fat_g": 64,
        "ingredients": [
            {"name": "green curry paste", "quantity": 3, "unit": "tbsp", "category": "spices"},
            {"name": "coconut milk", "quantity": 400, "unit": "ml", "category": "other"},
            {"name": "eggplant", "quantity": 2, "unit": "piece", "category": "vegetables"},
            {"name": "bamboo shoots", "quantity": 200, "unit": "g", "category": "vegetables"},
            {"name": "thai basil", "quantity": 20, "unit": "g", "category": "vegetables"},
        ],
    },
    {
        "cuisine": "Thai",
        "diet": "Vegetarian",
        "name": "Pad Thai (Tofu)",
        "description": "Rice noodles with tofu, peanuts, and tamarind-lime sauce.",
        "instructions": "1. Soak rice noodles.\n2. Stir-fry tofu; push aside.\n3. Scramble optional egg-free style or skip; add sauce and noodles.\n4. Toss with bean sprouts and peanuts.",
        "prep_time": 20,
        "cook_time": 15,
        "servings": 4,
        "calories_kcal": 1100,
        "protein_g": 40,
        "carbs_g": 160,
        "fat_g": 32,
        "ingredients": [
            {"name": "rice noodles", "quantity": 350, "unit": "g", "category": "grains"},
            {"name": "firm tofu", "quantity": 400, "unit": "g", "category": "other"},
            {"name": "tamarind paste", "quantity": 2, "unit": "tbsp", "category": "spices"},
            {"name": "roasted peanuts", "quantity": 60, "unit": "g", "category": "other"},
            {"name": "bean sprouts", "quantity": 150, "unit": "g", "category": "vegetables"},
        ],
    },
    {
        "cuisine": "Thai",
        "diet": "Vegetarian",
        "name": "Thai Papaya Salad",
        "description": "Shredded green papaya with chili, lime, and peanuts.",
        "instructions": "1. Pound garlic and chilies in a mortar.\n2. Add beans and papaya; bruise lightly.\n3. Dress with lime, fish sauce substitute (soy), and palm sugar.\n4. Top with peanuts and cherry tomatoes.",
        "prep_time": 20,
        "cook_time": 0,
        "servings": 4,
        "calories_kcal": 480,
        "protein_g": 12,
        "carbs_g": 64,
        "fat_g": 20,
        "ingredients": [
            {"name": "green papaya", "quantity": 500, "unit": "g", "category": "fruits"},
            {"name": "cherry tomato", "quantity": 150, "unit": "g", "category": "vegetables"},
            {"name": "roasted peanuts", "quantity": 50, "unit": "g", "category": "other"},
            {"name": "lime", "quantity": 3, "unit": "piece", "category": "fruits"},
            {"name": "green beans", "quantity": 100, "unit": "g", "category": "vegetables"},
        ],
    },
    {
        "cuisine": "Thai",
        "diet": "Vegetarian",
        "name": "Tom Yum Mushroom Soup",
        "description": "Hot and sour soup with lemongrass and mushrooms.",
        "instructions": "1. Simmer lemongrass, galangal, and lime leaves in stock.\n2. Add mushrooms and tomatoes.\n3. Season with lime juice and chili.\n4. Garnish with cilantro.",
        "prep_time": 15,
        "cook_time": 15,
        "servings": 4,
        "calories_kcal": 320,
        "protein_g": 16,
        "carbs_g": 32,
        "fat_g": 8,
        "ingredients": [
            {"name": "lemongrass", "quantity": 2, "unit": "stalk", "category": "vegetables"},
            {"name": "mushrooms", "quantity": 300, "unit": "g", "category": "vegetables"},
            {"name": "vegetable stock", "quantity": 1, "unit": "L", "category": "other"},
            {"name": "lime juice", "quantity": 4, "unit": "tbsp", "category": "fruits"},
            {"name": "thai chili", "quantity": 3, "unit": "piece", "category": "vegetables"},
        ],
    },
    {
        "cuisine": "Thai",
        "diet": "Vegetarian",
        "name": "Thai Basil Eggplant",
        "description": "Stir-fried eggplant with basil and chili garlic sauce.",
        "instructions": "1. Fry eggplant until golden; set aside.\n2. Stir-fry garlic and chilies.\n3. Return eggplant; add soy and sugar.\n4. Toss with Thai basil off heat.",
        "prep_time": 15,
        "cook_time": 15,
        "servings": 4,
        "calories_kcal": 560,
        "protein_g": 12,
        "carbs_g": 64,
        "fat_g": 28,
        "ingredients": [
            {"name": "eggplant", "quantity": 600, "unit": "g", "category": "vegetables"},
            {"name": "thai basil", "quantity": 30, "unit": "g", "category": "vegetables"},
            {"name": "garlic", "quantity": 5, "unit": "clove", "category": "vegetables"},
            {"name": "soy sauce", "quantity": 3, "unit": "tbsp", "category": "other"},
            {"name": "vegetable oil", "quantity": 3, "unit": "tbsp", "category": "other"},
        ],
    },
    # —— Thai · Non-vegetarian (5) ——
    {
        "cuisine": "Thai",
        "diet": "Non-vegetarian",
        "name": "Chicken Pad Thai",
        "description": "Classic pad thai with chicken and tamarind sauce.",
        "instructions": "1. Soak noodles.\n2. Stir-fry chicken; add sauce and noodles.\n3. Push aside; scramble eggs in the wok.\n4. Toss with sprouts and peanuts.",
        "prep_time": 20,
        "cook_time": 15,
        "servings": 4,
        "calories_kcal": 1400,
        "protein_g": 88,
        "carbs_g": 168,
        "fat_g": 48,
        "ingredients": [
            {"name": "rice noodles", "quantity": 350, "unit": "g", "category": "grains"},
            {"name": "chicken breast", "quantity": 500, "unit": "g", "category": "poultry"},
            {"name": "eggs", "quantity": 2, "unit": "piece", "category": "egg"},
            {"name": "tamarind paste", "quantity": 2, "unit": "tbsp", "category": "spices"},
            {"name": "roasted peanuts", "quantity": 60, "unit": "g", "category": "other"},
        ],
    },
    {
        "cuisine": "Thai",
        "diet": "Non-vegetarian",
        "name": "Thai Red Curry with Chicken",
        "description": "Spicy coconut red curry with chicken and vegetables.",
        "instructions": "1. Fry red curry paste in coconut cream.\n2. Add chicken; cook through.\n3. Add coconut milk and vegetables; simmer.\n4. Serve with jasmine rice and basil.",
        "prep_time": 15,
        "cook_time": 25,
        "servings": 4,
        "calories_kcal": 1500,
        "protein_g": 96,
        "carbs_g": 80,
        "fat_g": 88,
        "ingredients": [
            {"name": "chicken thigh", "quantity": 600, "unit": "g", "category": "poultry"},
            {"name": "red curry paste", "quantity": 3, "unit": "tbsp", "category": "spices"},
            {"name": "coconut milk", "quantity": 400, "unit": "ml", "category": "other"},
            {"name": "bell pepper", "quantity": 2, "unit": "piece", "category": "vegetables"},
            {"name": "thai basil", "quantity": 20, "unit": "g", "category": "vegetables"},
        ],
    },
    {
        "cuisine": "Thai",
        "diet": "Non-vegetarian",
        "name": "Tom Yum Goong",
        "description": "Hot and sour soup with prawns and lemongrass.",
        "instructions": "1. Simmer aromatics in stock.\n2. Add mushrooms and tomatoes.\n3. Add prawns; cook until pink.\n4. Finish with lime and cilantro.",
        "prep_time": 15,
        "cook_time": 12,
        "servings": 4,
        "calories_kcal": 480,
        "protein_g": 56,
        "carbs_g": 24,
        "fat_g": 12,
        "ingredients": [
            {"name": "prawns", "quantity": 500, "unit": "g", "category": "seafood"},
            {"name": "lemongrass", "quantity": 2, "unit": "stalk", "category": "vegetables"},
            {"name": "mushrooms", "quantity": 200, "unit": "g", "category": "vegetables"},
            {"name": "lime juice", "quantity": 4, "unit": "tbsp", "category": "fruits"},
            {"name": "fish sauce", "quantity": 2, "unit": "tbsp", "category": "other"},
        ],
    },
    {
        "cuisine": "Thai",
        "diet": "Non-vegetarian",
        "name": "Basil Chicken",
        "description": "Stir-fried minced chicken with holy basil and chili.",
        "instructions": "1. Pound garlic and chilies.\n2. Stir-fry chicken on high heat.\n3. Season with soy, fish sauce, and sugar.\n4. Toss in basil; serve over rice with fried egg optional.",
        "prep_time": 10,
        "cook_time": 10,
        "servings": 4,
        "calories_kcal": 1100,
        "protein_g": 80,
        "carbs_g": 96,
        "fat_g": 40,
        "ingredients": [
            {"name": "ground chicken", "quantity": 600, "unit": "g", "category": "poultry"},
            {"name": "thai basil", "quantity": 40, "unit": "g", "category": "vegetables"},
            {"name": "garlic", "quantity": 6, "unit": "clove", "category": "vegetables"},
            {"name": "fish sauce", "quantity": 2, "unit": "tbsp", "category": "other"},
            {"name": "jasmine rice", "quantity": 350, "unit": "g", "category": "grains"},
        ],
    },
    {
        "cuisine": "Thai",
        "diet": "Non-vegetarian",
        "name": "Thai Fish Cakes",
        "description": "Pan-fried fish cakes with red curry paste and beans.",
        "instructions": "1. Blend fish with curry paste, egg, and beans.\n2. Form patties.\n3. Pan-fry until golden.\n4. Serve with cucumber relish and sweet chili.",
        "prep_time": 20,
        "cook_time": 15,
        "servings": 4,
        "calories_kcal": 800,
        "protein_g": 72,
        "carbs_g": 32,
        "fat_g": 40,
        "ingredients": [
            {"name": "white fish fillet", "quantity": 600, "unit": "g", "category": "fish"},
            {"name": "red curry paste", "quantity": 2, "unit": "tbsp", "category": "spices"},
            {"name": "green beans", "quantity": 100, "unit": "g", "category": "vegetables"},
            {"name": "eggs", "quantity": 1, "unit": "piece", "category": "egg"},
            {"name": "cucumber", "quantity": 1, "unit": "piece", "category": "vegetables"},
        ],
    },
    # —— Mediterranean · Vegetarian (5) ——
    {
        "cuisine": "Mediterranean",
        "diet": "Vegetarian",
        "name": "Greek Salad",
        "description": "Tomatoes, cucumber, olives, and feta with oregano dressing.",
        "instructions": "1. Chop vegetables and feta.\n2. Whisk olive oil, lemon, and oregano.\n3. Toss salad gently.\n4. Serve chilled.",
        "prep_time": 15,
        "cook_time": 0,
        "servings": 4,
        "calories_kcal": 640,
        "protein_g": 24,
        "carbs_g": 24,
        "fat_g": 48,
        "ingredients": [
            {"name": "tomato", "quantity": 4, "unit": "piece", "category": "vegetables"},
            {"name": "cucumber", "quantity": 2, "unit": "piece", "category": "vegetables"},
            {"name": "feta cheese", "quantity": 200, "unit": "g", "category": "dairy"},
            {"name": "kalamata olives", "quantity": 100, "unit": "g", "category": "vegetables"},
            {"name": "olive oil", "quantity": 4, "unit": "tbsp", "category": "other"},
        ],
    },
    {
        "cuisine": "Mediterranean",
        "diet": "Vegetarian",
        "name": "Falafel Wrap",
        "description": "Crispy falafel in pita with tahini and salad.",
        "instructions": "1. Blend chickpeas with herbs; form balls.\n2. Bake or fry until crisp.\n3. Warm pita.\n4. Fill with falafel, lettuce, tomato, and tahini sauce.",
        "prep_time": 25,
        "cook_time": 20,
        "servings": 4,
        "calories_kcal": 1000,
        "protein_g": 36,
        "carbs_g": 120,
        "fat_g": 44,
        "ingredients": [
            {"name": "chickpeas", "quantity": 400, "unit": "g", "category": "grains"},
            {"name": "pita bread", "quantity": 4, "unit": "piece", "category": "grains"},
            {"name": "tahini", "quantity": 4, "unit": "tbsp", "category": "other"},
            {"name": "fresh parsley", "quantity": 30, "unit": "g", "category": "vegetables"},
            {"name": "lettuce", "quantity": 150, "unit": "g", "category": "vegetables"},
        ],
    },
    {
        "cuisine": "Mediterranean",
        "diet": "Vegetarian",
        "name": "Hummus Mezze Plate",
        "description": "Creamy hummus with warm pita and raw vegetables.",
        "instructions": "1. Blend chickpeas, tahini, lemon, and garlic until smooth.\n2. Swirl onto a plate; drizzle olive oil and paprika.\n3. Serve with pita wedges and vegetable sticks.",
        "prep_time": 15,
        "cook_time": 0,
        "servings": 4,
        "calories_kcal": 880,
        "protein_g": 32,
        "carbs_g": 96,
        "fat_g": 40,
        "ingredients": [
            {"name": "chickpeas", "quantity": 400, "unit": "g", "category": "grains"},
            {"name": "tahini", "quantity": 5, "unit": "tbsp", "category": "other"},
            {"name": "pita bread", "quantity": 4, "unit": "piece", "category": "grains"},
            {"name": "carrot sticks", "quantity": 200, "unit": "g", "category": "vegetables"},
            {"name": "lemon juice", "quantity": 3, "unit": "tbsp", "category": "fruits"},
        ],
    },
    {
        "cuisine": "Mediterranean",
        "diet": "Vegetarian",
        "name": "Mediterranean Roasted Vegetables",
        "description": "Oven-roasted zucchini, peppers, and eggplant with herbs.",
        "instructions": "1. Cut vegetables into chunks.\n2. Toss with olive oil, garlic, and herbs.\n3. Roast at 220°C until caramelized.\n4. Finish with balsamic glaze.",
        "prep_time": 15,
        "cook_time": 35,
        "servings": 4,
        "calories_kcal": 480,
        "protein_g": 12,
        "carbs_g": 48,
        "fat_g": 28,
        "ingredients": [
            {"name": "zucchini", "quantity": 2, "unit": "piece", "category": "vegetables"},
            {"name": "bell pepper", "quantity": 3, "unit": "piece", "category": "vegetables"},
            {"name": "eggplant", "quantity": 1, "unit": "piece", "category": "vegetables"},
            {"name": "olive oil", "quantity": 4, "unit": "tbsp", "category": "other"},
            {"name": "dried oregano", "quantity": 2, "unit": "tsp", "category": "spices"},
        ],
    },
    {
        "cuisine": "Mediterranean",
        "diet": "Vegetarian",
        "name": "Spinach Feta Pie",
        "description": "Phyllo pie with spinach, herbs, and feta.",
        "instructions": "1. Wilt spinach; squeeze dry.\n2. Mix with feta, herbs, and nutmeg.\n3. Layer phyllo with butter; fill and fold.\n4. Bake until golden and crisp.",
        "prep_time": 25,
        "cook_time": 40,
        "servings": 4,
        "calories_kcal": 1200,
        "protein_g": 40,
        "carbs_g": 80,
        "fat_g": 80,
        "ingredients": [
            {"name": "spinach", "quantity": 500, "unit": "g", "category": "vegetables"},
            {"name": "feta cheese", "quantity": 250, "unit": "g", "category": "dairy"},
            {"name": "phyllo pastry", "quantity": 12, "unit": "piece", "category": "grains"},
            {"name": "butter", "quantity": 80, "unit": "g", "category": "dairy"},
            {"name": "dill", "quantity": 20, "unit": "g", "category": "vegetables"},
        ],
    },
    # —— Mediterranean · Non-vegetarian (5) ——
    {
        "cuisine": "Mediterranean",
        "diet": "Non-vegetarian",
        "name": "Chicken Souvlaki",
        "description": "Grilled marinated chicken skewers with tzatziki.",
        "instructions": "1. Marinate chicken cubes in lemon, garlic, and oregano.\n2. Thread onto skewers; grill until charred.\n3. Serve with tzatziki and pita.\n4. Add tomato and onion if desired.",
        "prep_time": 20,
        "cook_time": 15,
        "servings": 4,
        "calories_kcal": 1100,
        "protein_g": 96,
        "carbs_g": 48,
        "fat_g": 48,
        "ingredients": [
            {"name": "chicken breast", "quantity": 600, "unit": "g", "category": "poultry"},
            {"name": "greek yogurt", "quantity": 200, "unit": "g", "category": "dairy"},
            {"name": "cucumber", "quantity": 1, "unit": "piece", "category": "vegetables"},
            {"name": "pita bread", "quantity": 4, "unit": "piece", "category": "grains"},
            {"name": "lemon", "quantity": 2, "unit": "piece", "category": "fruits"},
        ],
    },
    {
        "cuisine": "Mediterranean",
        "diet": "Non-vegetarian",
        "name": "Lamb Kofta",
        "description": "Spiced lamb skewers with garlic yogurt.",
        "instructions": "1. Mix lamb with onion, parsley, and spices.\n2. Form onto skewers.\n3. Grill or broil until cooked.\n4. Serve with rice pilaf or flatbread.",
        "prep_time": 20,
        "cook_time": 12,
        "servings": 4,
        "calories_kcal": 1400,
        "protein_g": 88,
        "carbs_g": 16,
        "fat_g": 104,
        "ingredients": [
            {"name": "ground lamb", "quantity": 600, "unit": "g", "category": "meat"},
            {"name": "onion", "quantity": 1, "unit": "piece", "category": "vegetables"},
            {"name": "fresh parsley", "quantity": 30, "unit": "g", "category": "vegetables"},
            {"name": "cumin", "quantity": 1, "unit": "tsp", "category": "spices"},
            {"name": "paprika", "quantity": 1, "unit": "tsp", "category": "spices"},
        ],
    },
    {
        "cuisine": "Mediterranean",
        "diet": "Non-vegetarian",
        "name": "Grilled Sea Bass",
        "description": "Whole grilled fish with lemon, olive oil, and herbs.",
        "instructions": "1. Score fish; season inside and out.\n2. Stuff with lemon and herbs.\n3. Grill or bake until flesh flakes.\n4. Drizzle olive oil before serving.",
        "prep_time": 15,
        "cook_time": 20,
        "servings": 4,
        "calories_kcal": 720,
        "protein_g": 88,
        "carbs_g": 4,
        "fat_g": 36,
        "ingredients": [
            {"name": "sea bass", "quantity": 800, "unit": "g", "category": "fish"},
            {"name": "lemon", "quantity": 2, "unit": "piece", "category": "fruits"},
            {"name": "olive oil", "quantity": 4, "unit": "tbsp", "category": "other"},
            {"name": "fresh thyme", "quantity": 10, "unit": "g", "category": "vegetables"},
            {"name": "garlic", "quantity": 4, "unit": "clove", "category": "vegetables"},
        ],
    },
    {
        "cuisine": "Mediterranean",
        "diet": "Non-vegetarian",
        "name": "Shakshuka",
        "description": "Eggs poached in spiced tomato and pepper sauce.",
        "instructions": "1. Sauté onion and peppers.\n2. Add tomatoes and spices; simmer.\n3. Make wells; crack eggs into sauce.\n4. Cover until whites set; serve with bread.",
        "prep_time": 10,
        "cook_time": 20,
        "servings": 4,
        "calories_kcal": 800,
        "protein_g": 40,
        "carbs_g": 48,
        "fat_g": 48,
        "ingredients": [
            {"name": "eggs", "quantity": 8, "unit": "piece", "category": "egg"},
            {"name": "crushed tomatoes", "quantity": 400, "unit": "g", "category": "vegetables"},
            {"name": "bell pepper", "quantity": 2, "unit": "piece", "category": "vegetables"},
            {"name": "onion", "quantity": 1, "unit": "piece", "category": "vegetables"},
            {"name": "cumin", "quantity": 1, "unit": "tsp", "category": "spices"},
        ],
    },
    {
        "cuisine": "Mediterranean",
        "diet": "Non-vegetarian",
        "name": "Seafood Paella",
        "description": "Saffron rice with shrimp, mussels, and peppers.",
        "instructions": "1. Sauté aromatics and peppers.\n2. Toast rice; add saffron stock.\n3. Simmer without stirring.\n4. Nestle seafood on top; cover until rice is tender.",
        "prep_time": 25,
        "cook_time": 35,
        "servings": 4,
        "calories_kcal": 1600,
        "protein_g": 88,
        "carbs_g": 200,
        "fat_g": 40,
        "ingredients": [
            {"name": "bomba rice", "quantity": 350, "unit": "g", "category": "grains"},
            {"name": "shrimp", "quantity": 300, "unit": "g", "category": "seafood"},
            {"name": "mussels", "quantity": 500, "unit": "g", "category": "seafood"},
            {"name": "saffron", "quantity": 0.5, "unit": "tsp", "category": "spices"},
            {"name": "bell pepper", "quantity": 2, "unit": "piece", "category": "vegetables"},
        ],
    },
    # —— American · Vegetarian (5) ——
    {
        "cuisine": "American",
        "diet": "Vegetarian",
        "name": "Mac and Cheese",
        "description": "Creamy baked cheddar pasta with breadcrumb topping.",
        "instructions": "1. Cook macaroni; drain.\n2. Make cheese sauce with butter, flour, milk, and cheddar.\n3. Combine pasta and sauce.\n4. Top with breadcrumbs; bake until golden.",
        "prep_time": 15,
        "cook_time": 25,
        "servings": 4,
        "calories_kcal": 1400,
        "protein_g": 56,
        "carbs_g": 160,
        "fat_g": 64,
        "ingredients": [
            {"name": "macaroni", "quantity": 400, "unit": "g", "category": "grains"},
            {"name": "cheddar cheese", "quantity": 300, "unit": "g", "category": "dairy"},
            {"name": "milk", "quantity": 500, "unit": "ml", "category": "dairy"},
            {"name": "butter", "quantity": 50, "unit": "g", "category": "dairy"},
            {"name": "breadcrumbs", "quantity": 80, "unit": "g", "category": "grains"},
        ],
    },
    {
        "cuisine": "American",
        "diet": "Vegetarian",
        "name": "Veggie Burger",
        "description": "Black bean patties with lettuce, tomato, and pickles.",
        "instructions": "1. Mash beans with oats, spices, and onion.\n2. Form patties; chill 15 minutes.\n3. Pan-fry or bake until crisp.\n4. Serve on buns with toppings.",
        "prep_time": 20,
        "cook_time": 15,
        "servings": 4,
        "calories_kcal": 1000,
        "protein_g": 36,
        "carbs_g": 128,
        "fat_g": 36,
        "ingredients": [
            {"name": "black beans", "quantity": 400, "unit": "g", "category": "grains"},
            {"name": "burger buns", "quantity": 4, "unit": "piece", "category": "grains"},
            {"name": "rolled oats", "quantity": 80, "unit": "g", "category": "grains"},
            {"name": "lettuce", "quantity": 100, "unit": "g", "category": "vegetables"},
            {"name": "tomato", "quantity": 2, "unit": "piece", "category": "vegetables"},
        ],
    },
    {
        "cuisine": "American",
        "diet": "Vegetarian",
        "name": "Caesar Salad",
        "description": "Romaine with parmesan, croutons, and creamy dressing.",
        "instructions": "1. Whisk dressing with garlic, lemon, and parmesan.\n2. Toss romaine with dressing.\n3. Top with extra parmesan and croutons.\n4. Serve immediately.",
        "prep_time": 15,
        "cook_time": 0,
        "servings": 4,
        "calories_kcal": 720,
        "protein_g": 28,
        "carbs_g": 48,
        "fat_g": 48,
        "ingredients": [
            {"name": "romaine lettuce", "quantity": 2, "unit": "head", "category": "vegetables"},
            {"name": "parmesan", "quantity": 80, "unit": "g", "category": "dairy"},
            {"name": "croutons", "quantity": 100, "unit": "g", "category": "grains"},
            {"name": "mayonnaise", "quantity": 4, "unit": "tbsp", "category": "other"},
            {"name": "lemon juice", "quantity": 2, "unit": "tbsp", "category": "fruits"},
        ],
    },
    {
        "cuisine": "American",
        "diet": "Vegetarian",
        "name": "BBQ Jackfruit Sandwich",
        "description": "Pulled jackfruit in smoky sauce on a soft bun.",
        "instructions": "1. Shred young jackfruit.\n2. Simmer with BBQ sauce until tender.\n3. Toast buns.\n4. Pile jackfruit on buns with coleslaw.",
        "prep_time": 15,
        "cook_time": 25,
        "servings": 4,
        "calories_kcal": 880,
        "protein_g": 12,
        "carbs_g": 160,
        "fat_g": 16,
        "ingredients": [
            {"name": "young jackfruit", "quantity": 500, "unit": "g", "category": "fruits"},
            {"name": "bbq sauce", "quantity": 250, "unit": "ml", "category": "other"},
            {"name": "burger buns", "quantity": 4, "unit": "piece", "category": "grains"},
            {"name": "coleslaw mix", "quantity": 200, "unit": "g", "category": "vegetables"},
            {"name": "apple cider vinegar", "quantity": 1, "unit": "tbsp", "category": "other"},
        ],
    },
    {
        "cuisine": "American",
        "diet": "Vegetarian",
        "name": "Corn Chowder",
        "description": "Creamy soup with sweet corn and potatoes.",
        "instructions": "1. Sauté onion and celery in butter.\n2. Add potatoes, corn, and stock; simmer.\n3. Blend half the soup for creaminess.\n4. Stir in cream; season with pepper.",
        "prep_time": 15,
        "cook_time": 30,
        "servings": 4,
        "calories_kcal": 960,
        "protein_g": 20,
        "carbs_g": 120,
        "fat_g": 48,
        "ingredients": [
            {"name": "sweet corn", "quantity": 400, "unit": "g", "category": "vegetables"},
            {"name": "potato", "quantity": 400, "unit": "g", "category": "vegetables"},
            {"name": "vegetable stock", "quantity": 800, "unit": "ml", "category": "other"},
            {"name": "heavy cream", "quantity": 150, "unit": "ml", "category": "dairy"},
            {"name": "celery", "quantity": 2, "unit": "stalk", "category": "vegetables"},
        ],
    },
    # —— American · Non-vegetarian (5) ——
    {
        "cuisine": "American",
        "diet": "Non-vegetarian",
        "name": "Classic Cheeseburger",
        "description": "Griddled beef patty with cheese on a toasted bun.",
        "instructions": "1. Form seasoned beef patties.\n2. Cook on a hot griddle to desired doneness.\n3. Melt cheese on patties.\n4. Assemble with lettuce, tomato, and pickles.",
        "prep_time": 15,
        "cook_time": 12,
        "servings": 4,
        "calories_kcal": 1800,
        "protein_g": 96,
        "carbs_g": 96,
        "fat_g": 112,
        "ingredients": [
            {"name": "ground beef", "quantity": 600, "unit": "g", "category": "meat"},
            {"name": "burger buns", "quantity": 4, "unit": "piece", "category": "grains"},
            {"name": "cheddar cheese", "quantity": 4, "unit": "slice", "category": "dairy"},
            {"name": "lettuce", "quantity": 100, "unit": "g", "category": "vegetables"},
            {"name": "pickles", "quantity": 12, "unit": "piece", "category": "vegetables"},
        ],
    },
    {
        "cuisine": "American",
        "diet": "Non-vegetarian",
        "name": "BBQ Chicken Wings",
        "description": "Oven-baked wings tossed in smoky barbecue sauce.",
        "instructions": "1. Season wings; bake until crisp.\n2. Toss in warm BBQ sauce.\n3. Return to oven 5 minutes.\n4. Serve with celery sticks and ranch.",
        "prep_time": 10,
        "cook_time": 40,
        "servings": 4,
        "calories_kcal": 1400,
        "protein_g": 112,
        "carbs_g": 48,
        "fat_g": 80,
        "ingredients": [
            {"name": "chicken wings", "quantity": 1, "unit": "kg", "category": "poultry"},
            {"name": "bbq sauce", "quantity": 200, "unit": "ml", "category": "other"},
            {"name": "celery", "quantity": 4, "unit": "stalk", "category": "vegetables"},
            {"name": "ranch dressing", "quantity": 100, "unit": "ml", "category": "dairy"},
            {"name": "smoked paprika", "quantity": 1, "unit": "tsp", "category": "spices"},
        ],
    },
    {
        "cuisine": "American",
        "diet": "Non-vegetarian",
        "name": "Fried Chicken",
        "description": "Buttermilk-marinated chicken with crispy seasoned crust.",
        "instructions": "1. Marinate chicken in buttermilk.\n2. Dredge in seasoned flour.\n3. Fry until golden and cooked through.\n4. Drain on a rack; rest 5 minutes.",
        "prep_time": 20,
        "cook_time": 25,
        "servings": 4,
        "calories_kcal": 2000,
        "protein_g": 120,
        "carbs_g": 80,
        "fat_g": 128,
        "ingredients": [
            {"name": "chicken pieces", "quantity": 1.2, "unit": "kg", "category": "poultry"},
            {"name": "buttermilk", "quantity": 500, "unit": "ml", "category": "dairy"},
            {"name": "flour", "quantity": 300, "unit": "g", "category": "grains"},
            {"name": "vegetable oil", "quantity": 1, "unit": "L", "category": "other"},
            {"name": "paprika", "quantity": 2, "unit": "tsp", "category": "spices"},
        ],
    },
    {
        "cuisine": "American",
        "diet": "Non-vegetarian",
        "name": "Clam Chowder",
        "description": "New England style creamy soup with clams and potatoes.",
        "instructions": "1. Cook bacon; sauté onion in drippings.\n2. Add potatoes and clam juice; simmer.\n3. Stir in clams and cream.\n4. Do not boil after cream is added.",
        "prep_time": 15,
        "cook_time": 25,
        "servings": 4,
        "calories_kcal": 1100,
        "protein_g": 64,
        "carbs_g": 80,
        "fat_g": 64,
        "ingredients": [
            {"name": "canned clams", "quantity": 400, "unit": "g", "category": "seafood"},
            {"name": "bacon", "quantity": 150, "unit": "g", "category": "pork"},
            {"name": "potato", "quantity": 400, "unit": "g", "category": "vegetables"},
            {"name": "heavy cream", "quantity": 200, "unit": "ml", "category": "dairy"},
            {"name": "onion", "quantity": 1, "unit": "piece", "category": "vegetables"},
        ],
    },
    {
        "cuisine": "American",
        "diet": "Non-vegetarian",
        "name": "Grilled Salmon",
        "description": "Lemon-dill salmon with roasted asparagus.",
        "instructions": "1. Season salmon; grill skin-side down.\n2. Roast asparagus with olive oil.\n3. Flip salmon briefly to finish.\n4. Serve with lemon wedges and dill.",
        "prep_time": 10,
        "cook_time": 15,
        "servings": 4,
        "calories_kcal": 1200,
        "protein_g": 96,
        "carbs_g": 16,
        "fat_g": 72,
        "ingredients": [
            {"name": "salmon fillet", "quantity": 600, "unit": "g", "category": "fish"},
            {"name": "asparagus", "quantity": 400, "unit": "g", "category": "vegetables"},
            {"name": "lemon", "quantity": 2, "unit": "piece", "category": "fruits"},
            {"name": "fresh dill", "quantity": 15, "unit": "g", "category": "vegetables"},
            {"name": "olive oil", "quantity": 3, "unit": "tbsp", "category": "other"},
        ],
    },
]
